### ISSUE TITLE
feat(soft_unique): add `__soft_unique__` helper

### ISSUE THREAD

**Issue by AxelThevenot** [AxelThevenot/dbt-assertions#15]
`__unique__` helper will flag duplicated rows but some usages requires to flag rows without having to remove all of them but keeping one version of each.

`__soft_unique__` can be a new helper replacing `1 = COUNT(1) OVER(...)` by `1 < ROW_NUMBER() OVER(...)`
But how to discriminate rows with an ordering ? 

Maybe rethink the v2 with 

```yml
__unique__:
    by:
        - key_1
        - key_2
    soft: true
    order_by: <str> | <List<str>>
```

```yml
__not_null__:
    by:
        - key_1
        - key_2
    layered: true
```
