### ISSUE TITLE
Why my assertion don't work ?

### ISSUE THREAD

**Issue by Francois-lenne** [AxelThevenot/dbt-assertions#34]
Hello, 

I try to use your package on a exemple in dbt cloud unfortunately this didn't work in my case :

# My table 

the csv of my source table separate by a comma
```
C_PAYS,D_ARCHIVE
ES,
FR,
PAYSSUPP,2022-11-17T13:12:32.287Z
UK,
```

# my yaml 

```
version: 2

models:
  - name: stg_d_site
    columns:
      - name: D_ARCHIVE
      - name: C_PAYS
      - name: exceptions
        assertions:
          D_ARCHIVE_is_not_null:
            description: 'D_ARCHIVE is not null.'
            expression: D_ARCHIVE IS NOT NULL

          site_trigram_format:
            description: 'Site trigram must contain 3 upper digits'
            expression: |
              LENGTH(C_PAYS) < 3

```

the other yaml 

```
version: 2

models:
  - name: stg_d_site
    tests:
      - dbt_assertions.generic_assertions:
          column: exceptions
          re_assert: true

    columns:
      - name: D_ARCHIVE
      - name: C_PAYS
        assertions:
          site_id_is_not_null:
            description: 'Site ID is not null.'
            expression: D_ARCHIVE IS NOT NULL

          site_trigram_format:
            description: 'Site trigram must contain 3 upper digits'
            expression: |
              LENGTH(C_PAYS) < 3
```

# the select model 

```
SELECT * ,
{{ dbt_assertions.assertions() | indent(4) }}
FROM {{ ref('stg_d_site') }}
WHERE {{ dbt_assertions.assertions_filter() }}
```

# the result in csv 

```
C_PAYS,D_ARCHIVE,EXCEPTIONS
ES,,[]
FR,,[]
PAYSSUPP,2022-11-17T13:12:32.287Z,[]
UK,,[]
```

# the compile code 

```
SELECT * ,
ARRAY_CONSTRUCT_COMPACT(
        CAST(NULL AS STRING)
    ) AS exceptions
FROM DB.dbt_flenne.stg_d_site
WHERE ARRAY_SIZE(exceptions) = 0
```

It seems to me that none of my assertion is working i wonder why because i retrieve the exemple model from this repository. 

Thanks in advance for your help

**Information**

- DB --> *snowflake*
- DBT CLOUD
- package version --> *1.4*

**Comment by AxelThevenot** [comment]
Oh ok I think I have understood the Issue :)

In "the other yaml" the columns `exceptions` is missing
If you can try with the following 

```yml
version: 2

models:
  - name: stg_d_site
    tests:
      - dbt_assertions.generic_assertions:
          column: exceptions
          re_assert: true

    columns:
      - name: D_ARCHIVE
      - name: C_PAYS
      - name: exceptions
        assertions:
          site_id_is_not_null:
            description: 'Site ID is not null.'
            expression: D_ARCHIVE IS NOT NULL

          site_trigram_format:
            description: 'Site trigram must contain 3 upper digits'
            expression: |
              LENGTH(C_PAYS) < 3
```
